# Generated by Django 4.2 on 2026-03-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_add_day_to_rainfall_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày dự đoán (ngày mai)', unique=True)),
                ('rf_pred', models.FloatField(help_text='Dự đoán từ RandomForest (mm)')),
                ('lr_pred', models.FloatField(help_text='Dự đoán từ LinearRegression (mm)')),
                ('xgb_pred', models.FloatField(help_text='Dự đoán từ XGBoost (mm)')),
                ('best_model', models.CharField(blank=True, help_text='Mô hình tốt nhất', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActualRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ngày có lượng mưa thực tế', unique=True)),
                ('actual_rainfall', models.FloatField(help_text='Lượng mưa thực tế (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rf_error', models.FloatField(blank=True, help_text='Sai số của RandomForest', null=True)),
                ('lr_error', models.FloatField(blank=True, help_text='Sai số của LinearRegression', null=True)),
                ('xgb_error', models.FloatField(blank=True, help_text='Sai số của XGBoost', null=True)),
                ('retrained', models.BooleanField(default=False, help_text='Đã retrain models chưa')),
                ('prediction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual', to='predictor.dailyprediction')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
